services:
    qdrant:
       image: qdrant/qdrant
       ports:
         - 6333:6333
       volumes:
         - qdrant-storage:/qdrant_storage/qdrant/storage
    redis:
       image: redis 
       ports:
         - 6379:6379

volumes:
   qdrant-storage: